- PROMETHEUS V1:
  - PROMETHEUS V1|EU28
  - PROMETHEUS V1|CHN
  - PROMETHEUS V1|IND
  - PROMETHEUS V1|NOAM
  - PROMETHEUS V1|WPAC
  - PROMETHEUS V1|EPROD
  - PROMETHEUS V1|CIS
  - PROMETHEUS V1|EMRG
  - PROMETHEUS V1|RESTW